---
title: "AnalyzingTheOtherTasks"
author: "Maria Eckstein"
date: "June 26, 2015"
output: pdf_document
---

```{r Load packages, echo = F, results = F, warning = F, message = F}
data_source = "2016"
do_exclude_trials = T                   # Exclude trials based on perseverance, RTs, etc?
ggsave_figures = T                      # Save figures as pngs onto the computer?
preprocess_data = F
home_dir = "C:/Users/maria/MEGAsync/TrainingPlanningProject"
figure_dir = file.path(home_dir, "TwoStepTask/model/RLDM")
data_dir = file.path(home_dir, "allResults/XlabData2016")
# model_dir = file.path(home_dir, "TwoStepTask/model")

source(file.path(home_dir, "TwoStepTask/model/TP_functions.R"))
library("reshape"); library("R.matlab"); library("car"); library("zoo"); library("plyr"); library("lme4"); library("lmerTest"); library("ggplot2"); theme_set(theme_bw()); library("gridExtra")
```

# Tower of London

+ Read in data set as `ToL` and set `numeric` and `factor` columns
+ Add column with minimum number of possible moves
+ Add columns indicating the subject `group` (model-free training session: `m_free`; model-based training session: `m_based`)
+ Save resulting data as .csv

```{r Prepare data, echo = F, warning = F}

ToL = read.table("auswertung_alle.txt",
                 header = T,
                 sep = " ", na.strings = "",
                 colClasses = c("factor", "factor", "factor", "factor", "numeric", "factor", "factor", "numeric", "factor", "numeric", "factor", "numeric", "numeric", "numeric", "numeric"))

ToL$run = substr(ToL$SubjID, 4, 4)
ToL$run = factor(ToL$run, labels = paste("Run", 1:4))
ToL$SubjID = as.numeric(substr(ToL$SubjID, 1, 3))

ToL$session = ToL$TaskVersion = NULL
  
ToL = add_performance_columns_ToL()   # Double-checked large numbers of moves in the raw data - everything matches up fine! 
ToL = add_group_columns(data = ToL)
summary(ToL)
write.table(ToL, file = "ToL_data.csv", quote = F, sep = ",", row.names = F)
```
```{r Plot ToL performance by participant, echo = F, warning = F, fig.height = 9, fig.width = 9}

# Which moves were optimal (minimum number of moves necessary)? Which were longer? 
gg_subj_moves = ggplot(ToL, aes(SubjID, MadeMoves, color = MadeMoves == MinMoves)) +
  # stat_summary(fun.data = mean_cl_normal, geom = "point", color = "black") +
  geom_point(alpha = .5) +
  coord_cartesian(ylim = c(0, 32)) +
  labs(y = "# moves for each tower", color = "Optimal solution found") +
  facet_wrap(~ run)
gg_subj_moves

# Difference between estimated and executed moves
gg_made_estim = ggplot(ToL, aes(SubjID, Made_minus_EstimMoves)) +
  stat_summary(fun.y = mean, geom = "bar", fill = "red") +
  geom_point(alpha = .5) +
  labs(x = "Subject ID", y = "Made moves - estimated moves") +
  facet_wrap(~ run)
gg_made_estim

# How much did each subject go over?
gg_made_min = ggplot(ToL, aes(SubjID, Made_minus_MinMoves)) +
  stat_summary(fun.y = mean, geom = "bar", fill = "red") +
  geom_point(alpha = .5) +
  labs(x = "Subject ID", y = "Made moves - min moves") +
  facet_wrap(~ run)
gg_made_min

# In which towers did a subject go over?
ToL$OptimSolution = ToL$MadeMoves == ToL$MinMoves
ToL$session[ToL$run %in% paste("Run", 1:2)] = 1
ToL$session[ToL$run %in% paste("Run", 3:4)] = 2
ToL_sum = ddply(ToL,
                .(SubjID, session, training), summarize,
                n_optim = sum(OptimSolution))
ToL_sum$ToL_median = ifelse(ToL_sum$n_optim > median(ToL_sum$n_optim, na.rm = T), "above", "below")

gg_subj_optim_perf = ggplot(ToL_sum, aes(session, n_optim)) +
  stat_summary(fun.data = mean_cl_normal, geom = "bar", fill = "red") +
  geom_point(alpha = .5, position = "jitter") +
  labs(x = "", y = "# towers solved perfectly") +
  facet_wrap(~ training)
gg_subj_optim_perf
```
```{r Create pad_perf, which will contain summary of behavior in all training tasks, echo = F, message = F, warning = F}
bad_perf = subset(ToL_sum, select = c("SubjID", "session", "n_optim", "ToL_median"))
colnames(bad_perf)[colnames(bad_perf) == "n_optim"] = "ToL_noptim"
```
```{r Plot general aspects of ToL performance, echo = F, eval = F}
## Also of interest?
# The more moves are necessary minimally, the more the deviation in the executed moves
gg_min_spread = ggplot(ToL, aes(MinMoves, MadeMoves, color = SubjID)) +
  geom_point(position = "jitter") +
  geom_abline(intercept = 0, slope = 1) +
  coord_cartesian(xlim = c(0, 20), ylim = c(0, 20))
gg_min_spread

# Usually, more moves are needed than previously estimated
gg_estim_spread = ggplot(ToL, aes(EstimMoves, MadeMoves, color = SubjID)) +
  geom_point(position = "jitter") +
  geom_abline(intercept = 0, slope = 1) +
  coord_cartesian(xlim = c(0, 25), ylim = c(0, 25))
```

# Food task

```{r Theoretical reward probabilities in food task, echo = F, warning = F, message = F}
prob_of_rewards = expand.grid(number_of_rewards = 0:8, rew_prob = seq(0.1, 0.3, 0.05), probability = NA, cum_probability = NA)
prob_of_rewards$rew_prob = factor(prob_of_rewards$rew_prob)

for (rew_prob in seq(0.1, 0.3, 0.05)) {
  cum_prob = 0
  for (numb_of_rew in 8:0) {
    prob = choose(8, numb_of_rew) * (rew_prob ^ numb_of_rew) * ((1 - rew_prob) ^ (8 - numb_of_rew))
    cum_prob = cum_prob + prob
    prob_of_rewards[prob_of_rewards$number_of_rewards == numb_of_rew &
                    prob_of_rewards$rew_prob == rew_prob, c("probability", "cum_probability")] = c(prob, cum_prob)
  }
}

gg_food_prob1 = ggplot(prob_of_rewards, aes(number_of_rewards, probability * 100, color = rew_prob, group = rew_prob)) +
  geom_point() +
  geom_line() +
  labs(x = "Number of rewards (trial)", y = "Probability (%)", color = "Rew. prob. / int.")

gg_food_prob2 = ggplot(prob_of_rewards, aes(number_of_rewards, cum_probability * 100, color = rew_prob, group = rew_prob)) +
  geom_point() +
  geom_line() +
  labs(x = "Number of rewards (trial)", y = "Cumulative probability (%)", color = "Rew. prob. / int.")

```
```{r Read in food data and summarize by trials, echo = F, warning = F, message = F}

if (preprocess_data) {
  col_names = c("SubjID", "run", "trial", "rew_avail", "rew_rec", "n_cor", "n_fal")
  food_dat = data.frame()
  filenames = list.files(data_dir, pattern = "FOOD_performance_.*.mat")
  
  for (filename in filenames) {
    
    ### Read in measures (columns= trials; rows= time points within trials)
    data = readMat(file.path(data_dir, filename))$data
    reward_schedule = as.data.frame(data[[1]])
    reward_received = as.data.frame(data[[2]])
    cor_key = as.data.frame(data[[3]])
    fal_key = as.data.frame(data[[4]])
    key_time = as.data.frame(data[[5]])
    
    ### Calculate trial means (sum over time points within trials)
    SubjID = substr(filename, 18, 20)
    run = substr(filename, 23, 23)
    if (run == "A") {run = "Run 1"
    } else if (run == "B") {run = "Run 2"
    } else if (run == "C") {run = "Run 3"
    } else if (run == "D") {run = "Run 4"
    }
    
    subj_dat = cbind(SubjID, run, 1:60, matrix(colSums(reward_schedule)), matrix(colSums(reward_received)), matrix(colSums(cor_key)), matrix(colSums(fal_key)))
    colnames(subj_dat) = col_names
    
    ### Add to food_dat
    food_dat = rbind(food_dat, subj_dat)
  }
  
  food_dat = add_group_columns(food_dat)
  write.csv(food_dat, file.path(data_dir, "food_dat.csv"), row.names = F)
}

food_dat = read.csv(file.path(data_dir, "food_dat.csv"))

### Remove break trials
trialwise_food_dat = ddply(food_dat, .(trial), summarize, n_cor = mean(n_cor, na.rm = T))
summary(trialwise_food_dat)
break_trials = subset(trialwise_food_dat, n_cor == 0)$trial
food_dat = subset(food_dat, !trial %in% break_trials)
    
head(food_dat)
summary(food_dat)
```
```{r Food performance over time, echo = F, message = F, warning = F}

gg_food_over_trials = ggplot(food_dat, aes(trial, n_cor, color = training, group = training)) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "pointrange") +
  labs(y = "# correct button presses / trial") +
  facet_wrap(~ run)
gg_food_over_trials

gg_food_over_trials2 = ggplot(food_dat, aes(trial, rew_rec - rew_avail, color = training, group = training)) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "pointrange") +
  labs(y = "(# received rewards - # available rewards) / trial") +
  facet_wrap(~ run)
gg_food_over_trials2

food_dat$session[food_dat$run %in% paste("Run", 1:2)] = 1
food_dat$session[food_dat$run %in% paste("Run", 3:4)] = 2
sum_food_dat = ddply(food_dat, .(SubjID, session, training, training_s1), summarize,
                     rew_rec = median(rew_rec, na.rm = T),
                     n_cor = median(n_cor, na.rm = T))
sum_food_dat$food_median = ifelse(sum_food_dat$n_cor > median(sum_food_dat$n_cor, na.rm = T), "above", "below")
summary(sum_food_dat)

gg_food_over_trials3 = ggplot(sum_food_dat, aes(session, n_cor, group = 1)) +
  stat_summary(fun.y = median, color = "red", geom = "point") +
  geom_point(alpha = .2, position = "jitter") +
  labs(y = "av. # correct button presses / trial") +
  facet_wrap(~ training)
gg_food_over_trials3

```
```{r Add food perf to bad_perf}

bad_perf = merge(subset(sum_food_dat, select = c("SubjID", "session", "n_cor", "food_median")),
                 bad_perf,
                 by = c("SubjID", "session"),
                 all = T)
colnames(bad_perf)[colnames(bad_perf) == "n_cor"] = "food_ncor"
summary(bad_perf)

```
```{r Food performance by subject, echo = F, message = F, warning = F}

gg_food_by_subj = ggplot(food_dat, aes(SubjID, n_cor, group = SubjID, color = training)) +
  stat_summary(fun.data = mean_cl_normal, geom = "pointrange") +
  labs(y = "# correct button presses / trial") +
  facet_wrap(~ session)
gg_food_by_subj

```

# Category tasks

```{r Read in category data, echo = F, message = F, warning = F}

if (preprocess_data) {
  col_names = c("SubjID", "run", "task", "trial", "ACC", "RT")
  cat_dat = data.frame()
  filenames = list.files(data_dir, pattern = "CAT0.*.mat")
  
  for (filename in filenames) {
    
    ### Get SubjID and run
    SubjID = substr(filename, 8, 10)
    run = substr(filename, 14, 14)
    task = substr(filename, 5, 6)
    if (run == "A") {run = "Run 1"
    } else if (run == "B") {run = "Run 2"
    } else if (run == "C") {run = "Run 3"
    } else if (run == "D") {run = "Run 4"
    }
    
    ### Read in measures (ACC & RT)
    exp = readMat(file.path(data_dir, filename))$exp
    index = dim(exp)[1] - 20
    
    if (dim(exp)[1] == 42 | (SubjID == "187" & run == "Run 4") | (SubjID == "149" & run == "Run 1")) {   # Participants with funny data sets...
      index = 21
    }
    if ((SubjID == "192" & run == "Run 4") | (SubjID == "193" & run == "Run 4")) {   # More funny data sets
    index = 23
    }
    
    ACC = matrix(exp[[index]][[1]])
    RT = matrix(exp[[index]][[2]])
    length(RT) = length(ACC)
    # key = matrix(exp[[index]][[4]])
    # theta = matrix(exp[[index]][[6]])
      
    ### Add to cat_dat
    subj_dat = cbind(SubjID, run, task, 1:length(ACC), ACC, RT)
    colnames(subj_dat) = col_names
    cat_dat = rbind(cat_dat, subj_dat)
  }
  cat_dat = subset(cat_dat, trial <= 110)   # only the first few participants got 120 trials
  cat_dat = add_group_columns(cat_dat)
  write.csv(cat_dat, file.path(data_dir, "cat_dat.csv"), row.names = F)
}
cat_dat = read.csv(file.path(data_dir, "cat_dat.csv"))

### Remove super-fast trials
cat_dat = subset(cat_dat, RT > 150 & !is.na(ACC))
    
summary(cat_dat)
head(cat_dat)

```
```{r Cateogry performance over time, echo = F, message = F, warning = F}

gg_cat_over_trials = ggplot(cat_dat, aes(trial, 100 * ACC, color = training, group = training)) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "pointrange", alpha = .5) +
  labs(y = "% correct classifications") +
  geom_hline(yintercept = 25) +
  geom_text(label = "chance", x = 95, y = 20, color = "black") +
  facet_grid(task ~ run)
gg_cat_over_trials

gg_cat_over_trials = ggplot(cat_dat, aes(trial, RT / 1000, color = training, group = training)) +
  stat_summary(fun.data = mean_cl_normal, geom = "pointrange", alpha = .5) +
  labs(y = "RT (sec)") +
  facet_grid(task ~ run)
gg_cat_over_trials

cat_dat$session[cat_dat$run %in% paste("Run", 1:2)] = 1
cat_dat$session[cat_dat$run %in% paste("Run", 3:4)] = 2
sum_cat_dat = ddply(cat_dat, .(SubjID, session, task, training, training_s1), summarize,
                    ACC = mean(ACC, na.rm = T),
                    RT = median(RT, na.rm = T))
ii_trials = subset(sum_cat_dat, task == "ii")$ACC
ii_median = median(ii_trials, na.rm = T)
sum_cat_dat$cat_median[sum_cat_dat$task == "ii"] = ifelse(ii_trials > ii_median, "above", "below")
rb_trials = subset(sum_cat_dat, task == "rb")$ACC
rb_median = median(rb_trials, na.rm = T)
sum_cat_dat$cat_median[sum_cat_dat$task == "rb"] = ifelse(rb_trials > rb_median, "above", "below")
summary(sum_cat_dat)

gg_cat_over_trials3 = ggplot(sum_cat_dat, aes(session, 100 * ACC, group = 1, color = task)) +
  stat_summary(fun.y = mean, geom = "point", color = "black") +
  geom_point(alpha = .5, position = "jitter") +
  geom_hline(yintercept = 25) +
  geom_text(label = "chance", x = 95, y = 20, color = "black") +
  facet_wrap(~ training)
gg_cat_over_trials3
```
```{r Add cat perf to bad_perf, echo = F, message = F, warning = F}
bad_perf = merge(bad_perf,
                 subset(sum_cat_dat, task == "ii", select = c("SubjID", "session", "ACC", "cat_median")),
                 all = T)
colnames(bad_perf)[colnames(bad_perf) %in% c("ACC", "cat_median")] = c("catii_ACC", "catii_median")

bad_perf = merge(bad_perf,
                 subset(sum_cat_dat, task == "rb", select = c("SubjID", "session", "ACC", "cat_median")),
                 all = T)
colnames(bad_perf)[colnames(bad_perf) %in% c("ACC", "cat_median")] = c("catrb_ACC", "catrb_median")

```
```{r Category performance by subject, echo = F, message = F, warning = F}

gg_cat_by_subj = ggplot(cat_dat, aes(SubjID, 100 * ACC, group = SubjID, color = training)) +
  stat_summary(fun.data = mean_cl_normal, geom = "pointrange") +
  labs(y = "ACC") +
  geom_hline(yintercept = 25) +
  geom_text(label = "chance", x = 200, y = 20, color = "black") +
  facet_grid(task ~ run)
gg_cat_by_subj

```

# Orientation discrimination

```{r read in data}

if (preprocess_data) {
  col_names = c("SubjID", "run", "trial", "ACC", "RT")
  ori_dat = data.frame()
  filenames = list.files(data_dir, pattern = "ROT.*.mat")   # ROT_105_1_A
  
  for (filename in filenames) {
    
    ### Get SubjID and run
    SubjID = substr(filename, 5, 7)
    run = substr(filename, 11, 11)
    if (run == "A") {run = "Run 1"
    } else if (run == "B") {run = "Run 2"
    } else if (run == "C") {run = "Run 3"
    } else if (run == "D") {run = "Run 4"
    }
    
    ### Read in measures (ACC & RT)
    exp = readMat(file.path(data_dir, filename))$exp
    
    ACC = matrix(exp[,,1]$ARROWdata[[1]])
    RT = matrix(exp[,,1]$ARROWdata[[2]])
    length(RT) = length(ACC)
      
    ### Add to ori_dat
    subj_dat = cbind(SubjID, run, 1:length(ACC), ACC, RT)
    colnames(subj_dat) = col_names
    ori_dat = rbind(ori_dat, subj_dat)
  }
  # ori_dat = subset(ori_dat, trial <= 65)   # only the first few participants got 120 trials
  ori_dat = add_group_columns(ori_dat)
  write.csv(ori_dat, file.path(data_dir, "ori_dat.csv"), row.names = F)
}
ori_dat = read.csv(file.path(data_dir, "ori_dat.csv"))

### Remove super-fast trials
ori_dat = subset(ori_dat, RT > 150 & !is.na(ACC))
    
summary(ori_dat)
head(ori_dat)

```
```{r Orientation performance over time, echo = F, message = F, warning = F}

gg_ori_over_trials = ggplot(ori_dat, aes(trial, 100 * ACC, color = training, group = training)) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "pointrange", alpha = .5) +
  labs(y = "% correct discrimination") +
  geom_hline(yintercept = 50) +
  geom_text(label = "chance", x = 60, y = 45, color = "black") +
  facet_grid( ~ run)
gg_ori_over_trials

ori_dat$session[ori_dat$run %in% paste("Run", 1:2)] = 1
ori_dat$session[ori_dat$run %in% paste("Run", 3:4)] = 2
sum_ori_dat = ddply(ori_dat, .(SubjID, session, training, training_s1), summarize,
                    ACC = mean(ACC, na.rm = T),
                    RT = median(RT, na.rm = T))
sum_ori_dat$ori_median = ifelse(sum_ori_dat$ACC > median(sum_ori_dat$ACC, na.rm = T), "above", "below")
summary(sum_ori_dat)

gg_ori_over_trials3 = ggplot(sum_ori_dat, aes(session, 100 * ACC, group = 1, color = ori_median)) +
  stat_summary(fun.y = mean, geom = "point", color = "black") +
  geom_point(alpha = .5, position = "jitter") +
  geom_hline(yintercept = 50) +
  geom_text(label = "chance", x = 3, y = 45, color = "black")
gg_ori_over_trials3
```
```{r Add ori perf to bad_perf, echo = F, message = F, warning = F}
bad_perf = merge(bad_perf,
                 subset(sum_ori_dat, select = c("SubjID", "session", "ACC", "ori_median")),
                 all = T)
colnames(bad_perf)[colnames(bad_perf) == "ACC"] = "ori_ACC"

```

# Number comparison

```{r read in data}

if (preprocess_data) {
  col_names = c("SubjID", "run", "trial", "ACC")
  num_dat = data.frame()
  filenames = list.files(data_dir, pattern = "NUM.*.mat")   # NUM_180_2_D
  
  for (filename in filenames) {
    
    ### Get SubjID and run
    SubjID = substr(filename, 5, 7)
    run = substr(filename, 11, 11)
    if (run == "A") {run = "Run 1"
    } else if (run == "B") {run = "Run 2"
    } else if (run == "C") {run = "Run 3"
    } else if (run == "D") {run = "Run 4"
    }
    
    ### Read in measures (ACC & RT)
    exp = readMat(file.path(data_dir, filename))$data
    ACC = matrix(exp[,,1]$correct)
      
    ### Add to num_dat
    subj_dat = cbind(SubjID, run, 1:length(ACC), ACC)
    colnames(subj_dat) = col_names
    num_dat = rbind(num_dat, subj_dat)
  }
  # num_dat = subset(num_dat, trial <= 65)   # only the first few participants got 120 trials
  num_dat = add_group_columns(num_dat)
  write.csv(num_dat, file.path(data_dir, "num_dat.csv"), row.names = F)
}
num_dat = read.csv(file.path(data_dir, "num_dat.csv"))
summary(num_dat)
head(num_dat)

```
```{r Number comparison performance over time, echo = F, message = F, warning = F}

gg_num_over_trials = ggplot(num_dat, aes(trial, 100 * ACC, color = training, group = training)) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "pointrange", alpha = .5) +
  labs(y = "% correct discrimination") +
  geom_hline(yintercept = 50) +
  geom_text(label = "chance", x = 50, y = 45, color = "black") +
  facet_grid( ~ run)
gg_num_over_trials

num_dat$session[num_dat$run %in% paste("Run", 1:2)] = 1
num_dat$session[num_dat$run %in% paste("Run", 3:4)] = 2
sum_num_dat = ddply(num_dat, .(SubjID, session, training, training_s1), summarize,
                    ACC = mean(ACC, na.rm = T))
sum_num_dat$num_median = ifelse(sum_num_dat$ACC > median(sum_num_dat$ACC, na.rm = T), "above", "below")
summary(sum_num_dat)

gg_num_over_trials3 = ggplot(sum_num_dat, aes(session, 100 * ACC, group = 1, color = num_median)) +
  stat_summary(fun.y = mean, geom = "point", color = "black") +
  geom_point(alpha = .5, position = "jitter")
gg_num_over_trials3
```
```{r Add num perf to bad_perf, echo = F, message = F, warning = F}
bad_perf = merge(bad_perf,
                 subset(sum_num_dat, select = c("SubjID", "session", "ACC", "num_median")),
                 all = T)
colnames(bad_perf)[colnames(bad_perf) == "ACC"] = "num_ACC"
head(bad_perf)
summary(bad_perf)
```

# All tasks together

```{r Add performance evaluation for each task to bad_perf, echo = F, message = F, warning = F}

# Save final bad_perf to disk
bad_perf = add_group_columns(bad_perf)
if (preprocess_data) {
  bad_perf$ToL_bad = ifelse(bad_perf$ToL_noptim < 2, T, F)
  bad_perf$food_bad = ifelse(bad_perf$food_ncor < 8, T, F)
  bad_perf$catii_bad = ifelse(bad_perf$catii_ACC < 0.3, T, F)
  bad_perf$catrb_bad = ifelse(bad_perf$catrb_ACC < 0.4, T, F)
  bad_perf$ori_bad = ifelse(bad_perf$ori_ACC < 0.5, T, F)
  bad_perf$num_bad = ifelse(bad_perf$num_ACC < 0.8, T, F)
  
  write.csv(bad_perf, file.path(data_dir, "bad_perf.csv"), row.names = F)
}

bad_perf = read.csv(file.path(data_dir, "bad_perf.csv"))

```
```{r Plot performance in tasks of the same session against each other, echo = F, message = F, warning = F}

# mf
gg_mftasks = ggplot(bad_perf, aes(food_ncor, 100 * catii_ACC, color = training, group = session)) +
  geom_point() +
  labs(x = "Food task (# correct buttons / trial)", y = "Category task ii (% correct trials)") +
  geom_smooth(method = lm, se = F, color = "black") +
  facet_wrap(~ session)
gg_mftasks

# mb
gg_mbtasks = ggplot(bad_perf, aes(ToL_noptim, catrb_ACC, color = training, group = session)) +
  geom_point(alpha = .5) +
  labs(x = "Tower of London (# optimal solutions / 5)", y = "Category task rb (% correct trials)") +
  geom_smooth(method = lm, se = F, color = "black") +
  facet_wrap(~ session)
gg_mbtasks

# co
gg_mbtasks = ggplot(bad_perf, aes(ori_ACC, num_ACC, color = training, group = session)) +
  geom_point(alpha = .5) +
  labs(x = "Orientation discrimination (% correct)", y = "Number comparison (% correct)") +
  geom_smooth(method = lm, se = F, color = "black") +
  facet_wrap(~ session)
gg_mbtasks

## Excluding participants with bad performance in these tasks
# mf
gg_mftasks = ggplot(subset(bad_perf, !(food_bad | catii_bad)), aes(food_ncor, 100 * catii_ACC, color = training, group = session)) +
  geom_point() +
  labs(x = "Food task (# correct buttons / trial)", y = "Category task ii (% correct trials)") +
  geom_smooth(method = lm, se = F, color = "black") +
  facet_wrap(~ session)
gg_mftasks

# mb
gg_mbtasks = ggplot(subset(bad_perf, !(ToL_bad | catrb_bad)), aes(ToL_noptim, catrb_ACC, color = training, group = session)) +
  geom_point(alpha = .5) +
  labs(x = "Tower of London (# optimal solutions / 5)", y = "Category task rb (% correct trials)") +
  geom_smooth(method = lm, se = F, color = "black") +
  facet_wrap(~ session)
gg_mbtasks

# control
gg_cotasks = ggplot(subset(bad_perf, !(ori_bad | num_bad)), aes(ori_ACC, num_ACC, color = training, group = session)) +
  geom_point(alpha = .5) +
  labs(x = "Orientation discrimination (% correct)", y = "Number comparison (% correct)") +
  geom_smooth(method = lm, se = F, color = "black") +
  facet_wrap(~ session)
gg_cotasks
```

# End

```{r Button to run all chunks}
```